name: CI/CD
on:
  push:
    branches:
      - busqueda-vuelos  # Cambia a la rama que corresponda

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11 (Zulu)
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'  # Usar Zulu JDK
          java-version: '11'
      - name: Build with Maven
        run: mvn clean install

  Deploy:
    needs: Build  # Indica que el trabajo Deploy depende de Build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/busqueda-vuelos'  # Ajusta el nombre de tu rama si es necesario
    steps:
      - uses: actions/checkout@v2
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker.io -y
      - name: Build Docker image
        run: docker build -t backendflightsearch .
      - name: Deploy to Vercel
        run: |
          vercel --prod --token=${{ secrets.VERCEL_TOKEN_BACKEND }} --confirm
